export const ON_TOGGLE_ITEM = 'COMPONENTS/ITEMS/ON_TOGGLE_ITEM';
export const ON_REMOVE_ITEM = 'COMPONENTS/ITEMS/ON_REMOVE_ITEM';
export const ON_UPDATE_PACKED_ITEM_FILTER = 'COMPONENTS/FILTER/ON_UPDATE_PACKED_ITEM_FILTER';
export const ON_UPDATE_UNPACKED_ITEM_FILTER = 'COMPONENTS/FILTER/ON_UPDATE_UNPACKED_ITEM_FILTER';